import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "./ui/button";
import { bookingUrl } from "./site-chrome";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-earth">{children}</p>; }
export function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="paper-texture bg-cream"><div className="mx-auto max-w-7xl px-5 py-18 md:px-8 md:py-28"><div className="max-w-3xl reveal-up"><Eyebrow>{eyebrow}</Eyebrow><h1 className="text-5xl leading-[0.96] text-primary md:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-base leading-8 text-ink-soft md:text-lg">{text}</p></div></div></section>; }
export function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="max-w-2xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="text-4xl leading-tight text-primary md:text-5xl">{title}</h2>{text && <p className="mt-5 leading-7 text-muted-foreground">{text}</p>}</div>; }
export function FinalCta({ title = "Vamos cuidar do seu sorriso com calma?" }: { title?: string }) { return <section className="bg-cream"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 py-16 md:flex-row md:items-center md:px-8 md:py-20"><div><Eyebrow>Seu cuidado começa aqui</Eyebrow><h2 className="max-w-2xl text-4xl text-primary md:text-5xl">{title}</h2></div><Button asChild size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Agendar minha consulta <ArrowRight /></a></Button></div></section>; }
export function TextLink({ to, children }: { to: "/sobre" | "/servicos" | "/resultados" | "/home-care" | "/contato"; children: React.ReactNode }) { return <Link to={to} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary underline decoration-accent underline-offset-8">{children}<ArrowRight className="size-4" /></Link>; }